name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0


      #### STEP CRIAÇÃO SERVIÇOS: EKS, RDS, S3 e CloudFront

      - name: Terraform Init (EKS-dcshp)
        run: terraform init
        working-directory: ./Infra-stg-tf/aws-eks-structure

      - name: Terraform Apply (EKS-dcshp)
        run: terraform apply -auto-approve
        working-directory: ./Infra-stg-tf/aws-eks-structure
        env:
          KUBECONFIG: ${{ runner.temp }}/.kube/config

       #### STEP CRIAÇÃO KUBECONFIG PARA GRAFANA
      - name: Create kubeconfig
        run: aws eks update-kubeconfig --name dcshp-eks-cluster-stg --region us-east-1
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init (RDS-dcshp)
        run: terraform init
        working-directory: ./Infra-stg-tf/aws-rds-structure

      - name: Terraform Apply (RDS-dcshp)
        run: terraform apply -auto-approve
        working-directory: ./Infra-stg-tf/aws-rds-structure

      - name: Terraform Init (S3-e-CloudFront-dcshp)
        run: terraform init
        working-directory: ./Infra-stg-tf/aws-s3-structure

      - name: Terraform Apply (S3-e-CloudFront-dcshp)
        run: terraform apply -auto-approve
        working-directory: ./Infra-stg-tf/aws-s3-structure
